server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_distributed_transaction_user_point?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

rocketmq:
  name-server: 192.168.136.128:9876
  consumer:
    topic: dtlm_topic
    group: my_group
    enable-msg-trace: true


